# Generated by Django 5.0.1 on 2024-01-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingIsCaringApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('foundation', 'Foundation'), ('nonprofit_organization', 'Nonprofit Organization'), ('local_collection', 'Local Collection')], default='fundacja', max_length=30)),
                ('categories', models.ManyToManyField(to='SharingIsCaringApp.category')),
            ],
        ),
    ]
